project:
  type: website
  resources: 
    - logo
execute:
  freeze: auto
  # # If any part of website shared using twitter, 
  # # Include spg handle in the
  #       twitter-card: 
  #          site: @spgatucsf
  resources: 
    - logo
    - images

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - custom_style/mobile_font_sizes.css
      - custom_style/navbar.css
      - custom_style/footer.css
      - custom_style/buttons.css
      - custom_style/homepage.css
      - custom_style/events_and_news_listings.css
      

website:
  page-navigation: true
  back-to-top-navigation: true
  draft-mode: unlinked
  title: "SPG at UCSF"
  
  search: 
    location: navbar
    type: textbox

######### Navigation bar (top of the website) ##############
  navbar:
    pinned: true
    search: true
    
    
    left:
      # Leadership page
      - href: leadership/index.qmd
        text: "Team"
      # Events page
      - href: events/index.qmd
        text: Events
      # News page
      - href: news/index.qmd
        text: News
      # Resources
      - href: resources/index.qmd
        text: Resources
      # Gallery
      - href: gallery/index.qmd
        text: Gallery

    right:
      # social media icons / links - 
      # icons are retrieved from:
      # https://icons.getbootstrap.com/
      - icon: bluesky
        href: https://bsky.app/profile/spgatucsf.bsky.social
        aria-label: Bluesky
      - icon: envelope-fill
        href: mailto:spgatucsf@gmail.com
        aria-label: Email
      # - icon: twitter
      #   href: https://twitter.com/spgatucsf
      #   aria-label: Twitter
      # - icon: facebook
      #   href: https://www.facebook.com/SPGatUCSF
      #   aria-label: Facebook
      # - icon: youtube
      #   href: https://www.youtube.com/@spgUCSF
        # aria-label: Youtube            
      - text: "<button class='btn btn-danger'>Join Us!</button>"
        href: join_info/index.qmd


############## Website footer ################
  page-footer:
    background: primary
    foreground: foreground
    left: 
      - text: |
          <medium>
          <b> &copy; Copyright 2021 - <span id="year"></span>, 
          Science Policy Group at UCSF </b>
          </medium>
          
          <script>
          document.getElementById("year").textContent = new Date().getFullYear();
          </script>
          
          <br>
          <small>
          The views and opinions of the RCO expressed herein do not necessarily state or reflect
          those of the Regents of the University of California, UCSF, UCSF
          Medical Center, or any entities or units thereof.
          </small>

    # social media icons / links - 
    # icons are retrieved from:
    # https://icons.getbootstrap.com/ 
    right:
      - text: "<br>"
      - icon: bluesky
        href: https://bsky.app/profile/spgatucsf.bsky.social
        aria-label: Bluesky
      - icon: envelope-fill
        href: mailto:spgatucsf@gmail.com
        aria-label: Email
      - icon: twitter
        href: https://twitter.com/spgatucsf
        aria-label: Twitter
      - icon: facebook
        href: https://www.facebook.com/SPGatUCSF
        aria-label: Facebook
      - icon: youtube
        href: https://www.youtube.com/@spgUCSF
        aria-label: Youtube




  

