---
title: "Science Diplomacy Career Panel (NSPN SciDip Roadshow)"
subtitle: "Mission Hall (MB)"
description: "This Science Diplomacy Career Panel will feature local SF diplomats, including Emilia Pasquier (CEO of Swissnex), and Martin Rauchbauer (Austrian tech diplomat). "
date: "2024-05-31"
categories: [Panel, Social]
date-format: medium 
---

### Speakers  
Emilia Pasquier (CEO, Swissnex),  
Martin Rauchbauer (Co-Founder, Tech Diplomacy Network),  
Nick Anthis (Senior Program Officer, UCOP)

This Science Diplomacy Career Panel will feature local SF diplomats, including Emilia Pasquier (CEO of Swissnex), and Martin Rauchbauer (Austrian tech diplomat). Our panel is co-hosted by the National Science Policy Network (NSPN), as part of their wider Science Diplomacy Roadshow held in various cities across the USA. The event will feature a 1-hour moderated panel discussion plus audience Q&A and followed by a networking reception with refreshments.

If you have ever wondered what science diplomacy entails, which skills you would need for a diplomatic career, or how scientific collaborations operate on an international scale, this is an excellent opportunity to learn more and network with local diplomats and NSPN members.

