name: Render and Publish

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
        # pre-release currently needed for bluesky icons - perhaps best to set a specific version later
          version: pre-release 

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        # requires renv.lock file 

      - name: Render site with --cache-refresh
        run: quarto render --cache-refresh

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false  # skip rendering again
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# 
#       - name: Publish to GitHub Pages (and render)
#         uses: quarto-dev/quarto-actions/publish@v2
#         with:
#           target: gh-pages
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

