name: Render and Publish

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

############ set up steps #####################
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
        # pre-release currently needed for bluesky icons - perhaps best to set a specific version later
          version: pre-release 

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

        # requires renv.lock file 
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

########## Render #####################        
        # Render site - but don't keep cache  
      - name: Render site 
        run: quarto render --cache-refresh

######### Publish ##################
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false  # skip rendering again
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

