name: Render Quarto Files into Published Website 

# on sets up how this workflow can be triggered
on:
  workflow_dispatch: # can be triggered through github (clicking workflow run)
  push: # is triggered every time we push (upload changes) to the github repository
    branches: main
    paths-ignore: # unless the change is one of these files / folders:
      - '_freeze/**'
      - '_site/**'
      - 'renv.lock'
      - 'README.md'
      - '.nojekyll'
      - '.gitignore'
      - '.github/workflows/*sheet*.yml'
      - '.github/workflows/*sheet*.yaml'
  workflow_run: # trigger every time we run one of the workflows building a page using a GDrive sheet
    workflows: 
      - "Update events Quarto files using GDrive sheet"
      - "Update news Quarto files using GDrive sheet"
      - "Update team/leadership Quarto files using GDrive sheet"
      - "Update gallery Quarto files using GDrive sheet"
    types:
      - completed
# Possibly to be added later, just uncomment
# set up - is trigged every day at 7am Pacific Time (12pm UTC)
  # schedule:
  #   - cron: "0 15 * * *"
      
concurrency:
  group: render-website
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

############ set up steps #####################
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'pre-release' # pre-release currently needed for bluesky icons - set a specific version when version 1.8.23 (or later) is stable
          
######### Publish ##################
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

