# .github/workflows/run-r-on-webhook.yml
name: Update events page of website using updated GDrive events sheet 

on:
  repository_dispatch:
    types: [update-events-sheets]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - main

concurrency:
  group: update-events-sheets
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-events-page:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Mask sheet URL
        run: echo "::add-mask::${{ secrets.EVENTS_GSHEET_URL }}"
        
      - name: Mask events github token
        run: echo "::add-mask::${{ secrets.EVENTS_GITHUB_TOKEN }}"

      - name: Mask gargle / Google drive token
        run: echo "::add-mask::${{ secrets.GDRIVE_KEY }}"  

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevent automatic token use for safety

      - name: Setup git auth
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.EVENTS_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Install ImageMagick dev libs (Ubuntu 24.04)
        run: |
              sudo apt-get update
              sudo apt-get install -y \
              imagemagick \
              libmagick++-6.q16-dev \
              libmagickwand-6.q16-dev \
              libmagickcore-6.q16-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.1'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Generate event webpage Quarto files from RScript
        run: Rscript events/convert_spreadsheet_to_events.R
        env:
          EVENTS_GSHEET_URL: ${{ secrets.EVENTS_GSHEET_URL }}
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
        # pre-release currently needed for bluesky icons - perhaps best to set a specific version later
          version: pre-release 

      - name: Render site
        run: quarto render 

      - name: Commit & push changes
        run: |
          git add events/
          git add _site/
          git status
          git commit -m "Update Events Page from SPG Events Google Sheet" || echo "No changes to commit"
          git push
