# .github/workflows/run-r-on-webhook.yml
name: Update events page of website using updated GDrive events sheet 

on:
  repository_dispatch:
    types: [update-events-sheets]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # branches:
    #   - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-events-page:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Mask sheet URL
        run: echo "::add-mask::${{ secrets.EVENTS_GSHEET_URL }}"
        
      - name: Mask events github token
        run: echo "::add-mask::${{ secrets.EVENTS_GITHUB_TOKEN }}"        

      - name: Mask gargle / Google drive token
        run: echo "::add-mask::${{ secrets.GARGLE_OAUTH_TOKEN }}"   

      - name: Mask gargle / Google drive email
        run: echo "::add-mask::${{ secrets.GARGLE_OAUTH_EMAIL }}"  

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevent automatic token use for safety

      - name: Setup git auth
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.EVENTS_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Use Gargle (Google Drive) OAuth token
        run: |
          mkdir -p ~/.R/gargle
          printf '%s' "${{ secrets.GARGLE_OAUTH_TOKEN }}" > ~/.R/gargle/gargle-oauth

      # - name: Use Gargle (Google Drive) OAuth token
      #   run: |
      #     mkdir -p ~/.R/gargle
      #     echo "${{ secrets.GARGLE_OAUTH_TOKEN }}" > ~/.R/gargle/gargle-oauth          

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
        # pre-release currently needed for bluesky icons - perhaps best to set a specific version later
          version: pre-release 

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.1'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Generate event webpage Quarto files from RScript
        run: Rscript events/convert_spreadsheet_to_events.R
        env:
          EVENTS_GSHEET_URL: ${{ secrets.EVENTS_GSHEET_URL }}
          GARGLE_OAUTH_EMAIL: ${{ secrets.GARGLE_OAUTH_EMAIL }}
          GARGLE_OAUTH_TOKEN: ${{ secrets.GARGLE_OAUTH_TOKEN }}

      - name: Commit changes
        run: |
          git status
          git add events/
          git commit -m "Update Events Page from SPG Events Google Sheet" || echo "No changes to commit"
          git push
