name: Update news Quarto files using GDrive sheet 

# on sets up how this workflow can be triggered
on:
  repository_dispatch:  # can be triggered via webhook (i.e. zapier zap)
    types: [update-news-sheets]
  workflow_dispatch:  # can be triggered through github (clicking workflow run)
    branches:
      - main
# Possibly to be added later, just uncomment
# set up - is trigged every day at 5am Pacific Time (12pm UTC)
  # schedule:
  #   - cron: "0 13 * * *"

concurrency:
  group: update-news-sheets
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-news-page:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Mask sheet URL
        run: echo "::add-mask::${{ secrets.NEWS_GSHEET_URL }}"
        
      - name: Mask github token
        run: echo "::add-mask::${{ secrets.PUSH_GITHUB_TOKEN }}"        

      - name: Mask gargle / Google drive token
        run: echo "::add-mask::${{ secrets.GDRIVE_KEY }}"  

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevent automatic token use for safety

      - name: Setup git auth
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PUSH_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.1'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Generate news page from build_news.R
        run: Rscript news/build_news.R
        env:
          NEWS_GSHEET_URL: ${{ secrets.NEWS_GSHEET_URL }}
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}

      - name: Commit & push changes
        run: |
          git status
          git pull --rebase origin main || echo "No changes to rebase"
          git add news
          git commit -m "Update News Page from SPG News Google Sheet" || echo "No changes to commit"
          git push
