name: Update team/leadership Quarto files using GDrive sheet 

# on sets up how this workflow can be triggered
on:
  repository_dispatch:
    types: [update-leadership-sheets]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - main
# Possibly to be added later, just uncomment
# set up - is trigged every day at 6am Pacific Time (12pm UTC)
  # schedule:
  #   - cron: "0 14 * * *"

concurrency:
  group: update-leadership-sheets
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-leadership-page:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Mask sheet URL
        run: echo "::add-mask::${{ secrets.LEADERSHIP_GSHEET_URL }}"
        
      - name: Mask github token
        run: echo "::add-mask::${{ secrets.PUSH_GITHUB_TOKEN }}"        

      - name: Mask gargle / Google drive token
        run: echo "::add-mask::${{ secrets.GDRIVE_KEY }}"  

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevent automatic token use for safety

      - name: Setup git auth
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PUSH_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Install ImageMagick dev libs (Ubuntu 24.04)
        run: |
              sudo apt-get update
              sudo apt-get install -y \
              imagemagick \
              libmagick++-6.q16-dev \
              libmagickwand-6.q16-dev \
              libmagickcore-6.q16-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.1'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Generate leadership team webpage Quarto files from RScript
        run: Rscript leadership/convert_spreadsheet_to_teampage.R
        env:
          LEADERSHIP_GSHEET_URL: ${{ secrets.LEADERSHIP_GSHEET_URL }}
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}

      - name: Commit & push changes
        run: |
          git status
          git pull --rebase origin main || echo "No changes to rebase"
          git add leadership/
          git commit -m "Update Team Page from SPG Leadership Google Sheet" || echo "No changes to commit"
          git push
