# .github/workflows/run-r-on-webhook.yml
name: Update gallery page of website using updated GDrive gallery sheet 

on:
  repository_dispatch:
    types: [update-gallery-sheets]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-gallery-page:
    runs-on: ubuntu-latest
    
    steps:       
      - name: Mask sheet URL
        run: echo "::add-mask::${{ secrets.GALLERY_GSHEET_URL }}"

      - name: Mask github token
        run: echo "::add-mask::${{ secrets.EVENTS_GITHUB_TOKEN }}"        

      # - name: Mask gargle / Google drive email
      #   run: echo "::add-mask::${{ secrets.GARGLE_OAUTH_KEY }}"  
        
      - name: Mask gargle / Google drive token
        run: echo "::add-mask::${{ secrets.GDRIVE_KEY }}"  

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # prevent automatic token use for safety

      - name: Setup git auth
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.EVENTS_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Install ImageMagick dev libs (Ubuntu 24.04)
        run: |
              sudo apt-get update
              sudo apt-get install -y \
              imagemagick \
              libmagick++-6.q16-dev \
              libmagickwand-6.q16-dev \
              libmagickcore-6.q16-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.3.1'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Generate gallery webpage Quarto files from RScript
        run: Rscript gallery/build_gallery_yml.R
        env:
          GALLERY_GSHEET_URL: ${{ secrets.GALLERY_GSHEET_URL }}
          GARGLE_OAUTH_KEY: ${{ secrets.GARGLE_OAUTH_KEY }}
          GDRIVE_KEY: ${{ secrets.GDRIVE_KEY }}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
        # pre-release currently needed for bluesky icons - perhaps best to set a specific version later
          version: pre-release 

      - name: Render site
        run: quarto render 

      - name: Commit & push changes
        run: |
          git add gallery/
          git add images/
          git add _site/
          git status
          git commit -m "Update Gallery Page from SPG Gallery Google Sheet" || echo "No changes to commit"
          git push
