---
title: |
  Voting Guide
subtitle: ""
description: "We at SPG have put together this voting guide including our endorsements for the San Francisco, California, and Federal elections. "
date: "2024-11-05"
categories: [Information]
date-format: medium 
---

We at SPG have put together this voting guide including our endorsements for the San Francisco, California, and Federal elections. We also included analysis of SF and California propositions, as well as East Bay State and Federal offices. Our positions are grounded in evidence-based information, with a specific focus on issues related to healthcare as relevant. If you are interested in learning more about any of the races or propositions, we have included links to sources with more comprehensive information. Though we are sharing our group's endorsements, we acknowledge the complexity behind many of the propositions on the ballot. Ultimately, our goal is to encourage everyone to participate in the democratic process and make informed voting decisions. Disclaimer: The positions we present in this voting guide are a reflection of our group's values and are not an official endorsement from UCSF.

